"""Markdown documentation formatter utility"""
from typing import List
from localdocs.parsers.base_parser import CodeElement


class MarkdownGenerator:
    """Utility designed to structure extracted code metadata into clean Markdown docs"""
    
    @staticmethod
    def generate(elements: List[CodeElement], project_name: str = "Project") -> str:
        """Generate a complete Markdown string from parsed system elements"""
        
        md = f"# {project_name} Documentation\n\n"
        md += "Generated by LocalDocs AI\n\n"
        md += "---\n\n"
        
        # Split elements into respective structural categories
        functions = [e for e in elements if e.type == "function"]
        classes = [e for e in elements if e.type == "class"]
        methods = [e for e in elements if e.type == "method"]
        
        md += "## Overview\n\n"
        md += f"- **{len(functions)}** functions\n"
        md += f"- **{len(classes)}** classes\n"
        md += f"- **{len(methods)}** methods\n\n"
        md += "---\n\n"
        
        # Format Top-Level Functions
        if functions:
            md += "## Functions\n\n"
            for func in functions:
                md += MarkdownGenerator._format_function(func)
        
        # Format Classes and their inner methods
        if classes:
            md += "## Classes\n\n"
            for cls in classes:
                md += MarkdownGenerator._format_class(cls, elements)
        
        return md
    
    @staticmethod
    def _format_function(func: CodeElement) -> str:
        md = f"### `{func.name}()`\n\n"
        if func.description:
            md += f"{func.description}\n\n"
        if func.parameters:
            md += "**Parameters:**\n"
            for param in func.parameters:
                md += f"- `{param}`\n"
            md += "\n"
        md += "---\n\n"
        return md
    
    @staticmethod
    def _format_class(cls: CodeElement, elements: List[CodeElement]) -> str:
        md = f"### Class: `{cls.name}`\n\n"
        if cls.description:
            md += f"{cls.description}\n\n"
        
        # Filter for methods belonging strictly to this class object container
        methods = [e for e in elements if e.type == "method" and e.name.startswith(f"{cls.name}.")]
        if methods:
            md += "**Methods:**\n"
            for method in methods:
                # Creates a clean local markdown anchor reference link
                anchor_link = method.name.lower().replace('.', '')
                md += f"- [`{method.name}()`](#{anchor_link})\n"
            md += "\n"
        
        md += "---\n\n"
        return md
