"""Markdown documentation generator"""
from typing import List
from localdocs.parsers.base_parser import CodeElement


class MarkdownGenerator:
    @staticmethod
    def generate(elements: List[CodeElement], project_name: str = "Project") -> str:
        md = f"# {project_name} Systems Documentation\n"
        md += "Generated by LocalDocs AI Universal Pipeline Engine\n"
        md += "---\n\n"
        
        functions = [e for e in elements if e.type == "function"]
        classes = [e for e in elements if e.type == "class"]
        methods = [e for e in elements if e.type == "method"]
        
        md += "## 📊 Architecture Overview\n"
        md += f"- **Total System Functions:** {len(functions)}\n"
        md += f"- **Total Object Classes:** {len(classes)}\n"
        md += f"- **Total Class Methods:** {len(methods)}\n"
        md += "---\n\n"
        
        if not elements:
            md += "> ⚠️ **Warning:** No code elements were detected. Ensure your code is syntactically correct.\n\n---\n\n"
        
        if functions:
            md += "## 📝 Functions\n\n"
            for func in functions:
                md += MarkdownGenerator._format_function(func)
            md += "---\n\n"
        
        if classes:
            md += "## 🏗️ Classes\n\n"
            for cls in classes:
                md += MarkdownGenerator._format_class(cls, elements)
        
        return md
    
    @staticmethod
    def _format_function(func: CodeElement) -> str:
        md = f"### `{func.name}()`\n\n"
        if hasattr(func, 'description') and func.description:
            md += f"{func.description}\n\n"
        if hasattr(func, 'parameters') and func.parameters:
            md += "**Parameters:**\n"
            for param in func.parameters:
                md += f"- `{param}`\n"
            md += "\n"
        md += f"*Line {getattr(func, 'line_number', 1)}*\n\n"
        return md
    
    @staticmethod
    def _format_class(cls: CodeElement, elements: List[CodeElement]) -> str:
        md = f"### `class {cls.name}`\n\n"
        if hasattr(cls, 'description') and cls.description:
            md += f"{cls.description}\n\n"
        
        methods = [e for e in elements if e.type == "method" and e.name.startswith(f"{cls.name}.")]
        if methods:
            md += "**Methods:**\n"
            for method in methods:
                md += f"- `{method.name}()`\n"
            md += "\n"
        
        md += f"*Line {getattr(cls, 'line_number', 1)}*\n\n"
        return md
