"""
API Routes with Prompt Injection Protection
===========================================
All endpoints now include security validation before processing
"""

from fastapi import APIRouter, HTTPException
from typing import List, Dict, Any
import logging
from datetime import datetime

from localdocs.api.schemas import (
    GenerateDocsRequest,
    GenerateDocsResponse,
    HealthCheckResponse
)
from localdocs.parsers.python_parser import PythonParser
from localdocs.security.prompt_injection import validate_and_sanitize_prompt, get_injection_detector

# Configure logging
logger = logging.getLogger(__name__)

router = APIRouter()


@router.get("/", response_model=HealthCheckResponse)
async def root():
    """Root endpoint - health check."""
    return HealthCheckResponse(
        message="Welcome to LocalDocs AI",
        version="1.0.0",
        docs="/docs"
    )


@router.post("/api/v1/generate-docs", response_model=GenerateDocsResponse)
async def generate_docs(request: GenerateDocsRequest):
    """
    Generate documentation for code with prompt injection protection.
    """
    try:
        logger.info(f"[SECURITY] Validating input length: {len(request.code)} chars")
        
        sanitized_code = validate_and_sanitize_prompt(request.code)
        
        if len(sanitized_code) > 50000:
            raise HTTPException(
                status_code=400,
                detail="Code exceeds maximum allowed length (50000 characters)"
            )
        
        logger.info(f"[SECURITY] Input validated successfully")
        
        parser = PythonParser(sanitized_code)
        elements = parser.parse()
        
        if not elements:
            logger.warning("No code elements found in input")
            return GenerateDocsResponse(
                success=True,
                documentation="No functions, classes, or methods detected in the provided code.",
                elements_count=0,
                elements=[]
            )
        
        logger.info(f"Generating docs for {len(elements)} elements")
        
        # Mock documentation (Ollama temporarily disabled)
        documentation = "Documentation will be generated by Ollama when it's connected."
        
        is_valid, error_msg = get_injection_detector().validate_input(
            documentation, 
            max_length=50000
        )
        
        if not is_valid:
            logger.warning(f"LLM output failed validation: {error_msg}")
            documentation = "Documentation generated but filtered due to security concerns."
        
        return GenerateDocsResponse(
            success=True,
            documentation=documentation,
            elements_count=len(elements),
            elements=[
                {
                    "name": e.name,
                    "type": e.type,
                    "description": e.description
                }
                for e in elements
            ]
        )
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error generating docs: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Error: {str(e)}")


@router.post("/api/v1/parse-code")
async def parse_code(code: str, language: str = "python"):
    """
    Parse code without generating docs (for testing).
    """
    try:
        sanitized_code = validate_and_sanitize_prompt(code)
        
        if language == "python":
            parser = PythonParser(sanitized_code)
            elements = parser.parse()
            
            return {
                "success": True,
                "elements": [
                    {"name": e.name, "type": e.type, "description": e.description}
                    for e in elements
                ],
                "count": len(elements)
            }
        else:
            raise HTTPException(status_code=400, detail=f"Unsupported language: {language}")
            
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error parsing code: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Error: {str(e)}")


@router.get("/api/v1/security/status")
async def security_status():
    """Security status endpoint - shows active security features."""
    detector = get_injection_detector()
    
    return {
        "security_enabled": True,
        "prompt_injection_protection": True,
        "patterns_detected": len(detector.INJECTION_PATTERNS),
        "features": [
            "Prompt injection detection",
            "Input validation & sanitization",
            "Length limits (10,000 chars)",
            "Special character monitoring",
            "Request logging",
            "XSS protection",
            "SQL injection protection"
        ]
    }


@router.post("/api/v1/test-security")
async def test_security(request: dict):
    test_input = request.get("test_input", "")
    """Test endpoint to validate security detection."""
    detector = get_injection_detector()
    
    is_injection, pattern = detector.detect_injection(test_input)
    is_valid, validation_msg = detector.validate_input(test_input)
    
    return {
        "input_length": len(test_input),
        "is_malicious": is_injection,
        "pattern_matched": pattern,
        "is_valid": is_valid,
        "validation_message": validation_msg,
        "sanitized": detector.sanitize_input(test_input) if not is_injection else None
    }
